--
-- Author: Faizan Noor <admin@FaizanNoor.com>
-- URL: www.FaizanNoor.com
-- Description: List of all Countries of the world.

-- --------------------------------------------------------
--
-- Table structure for table `countries`
--

CREATE TABLE IF NOT EXISTS `countries` (
  `id` smallint(4) NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `full_name` varchar(80) DEFAULT NULL,
  `iso2` char(2) DEFAULT NULL COMMENT 'ISO alpha-2 code',
  `iso3` char(3) DEFAULT NULL COMMENT 'ISO alpha-3 code',
  `continent_name` varchar(24) DEFAULT NULL,
  `currency_name` varchar(32) DEFAULT NULL,
  `currency_code` char(3) DEFAULT NULL,
  `currency_symbol` varchar(3) DEFAULT NULL,
  `calling_code` varchar(8) DEFAULT NULL COMMENT 'International dialing code',
  `numeric_code` varchar(6) DEFAULT NULL COMMENT 'United Nations numerical code M49 for countries',
  `postal_code` varchar(45) DEFAULT NULL COMMENT 'Pattern for postal code of the country.',
  `un_member` varchar(12) DEFAULT NULL,
  `cctld` varchar(5) DEFAULT NULL COMMENT 'country code top-level domain',
  `flag` varchar(6) DEFAULT NULL COMMENT 'Flag image name with extension',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Active = 1, Inactive = 0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `countries_uq_name` (`name`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

--
-- Dumping data for table `countries`
--

INSERT INTO `countries` (`id`, `name`, `full_name`, `iso2`, `iso3`, `continent_name`, `currency_name`, `currency_code`, `currency_symbol`, `calling_code`, `numeric_code`, `postal_code`, `un_member`, `cctld`, `flag`, `is_active`) VALUES
(1, 'Afghanistan', 'Islamic Republic of Afghanistan', 'AF', 'AFG', 'Asia', 'Afghani', 'AFN', '؋', '93', '004', NULL, 'yes', '.af', 'AF.png', 1),
(2, 'Aland Islands', '&Aring;land Islands', 'AX', 'ALA', 'Europe', NULL, NULL, NULL, '358', '248', NULL, 'no', '.ax', 'AX.png', 1),
(3, 'Albania', 'Republic of Albania', 'AL', 'ALB', 'Europe', 'Lek', 'ALL', 'Lek', '355', '008', NULL, 'yes', '.al', 'AL.png', 1),
(4, 'Algeria', 'People''s Democratic Republic of Algeria', 'DZ', 'DZA', NULL, 'Dinar', 'DZD', '', '213', '012', NULL, 'yes', '.dz', 'DZ.png', 1),
(5, 'American Samoa', 'American Samoa', 'AS', 'ASM', 'Australia/Oceania', 'Dollar', 'USD', '$', '1+684', '016', NULL, 'no', '.as', 'AS.png', 1),
(6, 'Andorra', 'Principality of Andorra', 'AD', 'AND', 'Europe', 'Euro', 'EUR', '€', '376', '020', NULL, 'yes', '.ad', 'AD.png', 1),
(7, 'Angola', 'Republic of Angola', 'AO', 'AGO', NULL, 'Kwanza', 'AOA', 'Kz', '244', '024', NULL, 'yes', '.ao', 'AO.png', 1),
(8, 'Anguilla', 'Anguilla', 'AI', 'AIA', 'North America', 'Dollar', 'XCD', '$', '1+264', '660', NULL, 'no', '.ai', 'AI.png', 1),
(9, 'Antarctica', 'Antarctica', 'AQ', 'ATA', 'Antarctica', NULL, NULL, NULL, '672', '010', NULL, 'no', '.aq', 'AQ.png', 1),
(10, 'Antigua and Barbuda', 'Antigua and Barbuda', 'AG', 'ATG', 'North America', 'Dollar', 'XCD', '$', '1+268', '028', NULL, 'yes', '.ag', 'AG.png', 1),
(11, 'Argentina', 'Argentine Republic', 'AR', 'ARG', 'South America', 'Peso', 'ARS', '$', '54', '032', NULL, 'yes', '.ar', 'AR.png', 1),
(12, 'Armenia', 'Republic of Armenia', 'AM', 'ARM', 'Asia', 'Dram', 'AMD', '', '374', '051', NULL, 'yes', '.am', 'AM.png', 1),
(13, 'Aruba', 'Aruba', 'AW', 'ABW', 'North America', 'Guilder', 'AWG', 'ƒ', '297', '533', NULL, 'no', '.aw', 'AW.png', 1),
(14, 'Australia', 'Commonwealth of Australia', 'AU', 'AUS', 'Australia/Oceania', 'Dollar', 'AUD', '$', '61', '036', NULL, 'yes', '.au', 'AU.png', 1),
(15, 'Austria', 'Republic of Austria', 'AT', 'AUT', 'Europe', 'Euro', 'EUR', '€', '43', '040', NULL, 'yes', '.at', 'AT.png', 1),
(16, 'Azerbaijan', 'Republic of Azerbaijan', 'AZ', 'AZE', 'Asia', 'Manat', 'AZN', 'ман', '994', '031', NULL, 'yes', '.az', 'AZ.png', 1),
(17, 'Bahamas', 'Commonwealth of The Bahamas', 'BS', 'BHS', 'North America', 'Dollar', 'BSD', '$', '1+242', '044', NULL, 'yes', '.bs', 'BS.png', 1),
(18, 'Bahrain', 'Kingdom of Bahrain', 'BH', 'BHR', 'Asia', 'Dinar', 'BHD', '', '973', '048', NULL, 'yes', '.bh', 'BH.png', 1),
(19, 'Bangladesh', 'People''s Republic of Bangladesh', 'BD', 'BGD', 'Asia', 'Taka', 'BDT', '', '880', '050', NULL, 'yes', '.bd', 'BD.png', 1),
(20, 'Barbados', 'Barbados', 'BB', 'BRB', 'North America', 'Dollar', 'BBD', '$', '1+246', '052', NULL, 'yes', '.bb', 'BB.png', 1),
(21, 'Belarus', 'Republic of Belarus', 'BY', 'BLR', 'Europe', 'Ruble', 'BYR', 'p.', '375', '112', NULL, 'yes', '.by', 'BY.png', 1),
(22, 'Belgium', 'Kingdom of Belgium', 'BE', 'BEL', 'Europe', 'Euro', 'EUR', '€', '32', '056', NULL, 'yes', '.be', 'BE.png', 1),
(23, 'Belize', 'Belize', 'BZ', 'BLZ', 'North America', 'Dollar', 'BZD', 'BZ$', '501', '084', NULL, 'yes', '.bz', 'BZ.png', 1),
(24, 'Benin', 'Republic of Benin', 'BJ', 'BEN', NULL, 'Franc', 'XOF', '', '229', '204', NULL, 'yes', '.bj', 'BJ.png', 1),
(25, 'Bermuda', 'Bermuda Islands', 'BM', 'BMU', 'North America', 'Dollar', 'BMD', '$', '1+441', '060', NULL, 'no', '.bm', 'BM.png', 1),
(26, 'Bhutan', 'Kingdom of Bhutan', 'BT', 'BTN', 'Asia', 'Ngultrum', 'BTN', '', '975', '064', NULL, 'yes', '.bt', 'BT.png', 1),
(27, 'Bolivia', 'Plurinational State of Bolivia', 'BO', 'BOL', 'South America', 'Boliviano', 'BOB', '$b', '591', '068', NULL, 'yes', '.bo', 'BO.png', 1),
(28, 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', NULL, NULL, NULL, NULL, '599', '535', NULL, 'no', '.bq', 'BQ.png', 1),
(29, 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH', 'Europe', 'Marka', 'BAM', 'KM', '387', '070', NULL, 'yes', '.ba', 'BA.png', 1),
(30, 'Botswana', 'Republic of Botswana', 'BW', 'BWA', NULL, 'Pula', 'BWP', 'P', '267', '072', NULL, 'yes', '.bw', 'BW.png', 1),
(31, 'Bouvet Island', 'Bouvet Island', 'BV', 'BVT', 'Antarctica', 'Krone', 'NOK', 'kr', 'NONE', '074', '', 'no', '.bv', 'BV.png', 1),
(32, 'Brazil', 'Federative Republic of Brazil', 'BR', 'BRA', 'South America', 'Real', 'BRL', 'R$', '55', '076', '^(d{8})$', 'yes', '.br', 'BR.png', 1),
(33, 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'IO', 'IOT', 'Asia', 'Dollar', 'USD', '$', '246', '086', '', 'no', '.io', 'IO.png', 1),
(34, 'Brunei', 'Brunei Darussalam', 'BN', 'BRN', 'Asia', 'Dollar', 'BND', '$', '673', '096', '^([A-Z]{2}d{4})$', 'yes', '.bn', 'BN.png', 1),
(35, 'Bulgaria', 'Republic of Bulgaria', 'BG', 'BGR', 'Europe', 'Lev', 'BGN', 'лв', '359', '100', '^(d{4})$', 'yes', '.bg', 'BG.png', 1),
(36, 'Burkina Faso', 'Burkina Faso', 'BF', 'BFA', NULL, 'Franc', 'XOF', '', '226', '854', '', 'yes', '.bf', 'BF.png', 1),
(37, 'Burundi', 'Republic of Burundi', 'BI', 'BDI', NULL, 'Franc', 'BIF', '', '257', '108', '', 'yes', '.bi', 'BI.png', 1),
(38, 'Cambodia', 'Kingdom of Cambodia', 'KH', 'KHM', 'Asia', 'Riels', 'KHR', '៛', '855', '116', '^(d{5})$', 'yes', '.kh', 'KH.png', 1),
(39, 'Cameroon', 'Republic of Cameroon', 'CM', 'CMR', NULL, 'Franc', 'XAF', 'FCF', '237', '120', '', 'yes', '.cm', 'CM.png', 1),
(40, 'Canada', 'Canada', 'CA', 'CAN', 'North America', 'Dollar', 'CAD', '$', '1', '124', '^([a-zA-Z]d[a-zA-Z]d[a-zA-Z]d)$', 'yes', '.ca', 'CA.png', 1),
(41, 'Cape Verde', 'Republic of Cape Verde', 'CV', 'CPV', NULL, 'Escudo', 'CVE', '', '238', '132', '^(d{4})$', 'yes', '.cv', 'CV.png', 1),
(42, 'Cayman Islands', 'The Cayman Islands', 'KY', 'CYM', 'North America', 'Dollar', 'KYD', '$', '1+345', '136', '', 'no', '.ky', 'KY.png', 1),
(43, 'Central African Republic', 'Central African Republic', 'CF', 'CAF', NULL, 'Franc', 'XAF', 'FCF', '236', '140', '', 'yes', '.cf', 'CF.png', 1),
(44, 'Chad', 'Republic of Chad', 'TD', 'TCD', NULL, 'Franc', 'XAF', '', '235', '148', '', 'yes', '.td', 'TD.png', 1),
(45, 'Chile', 'Republic of Chile', 'CL', 'CHL', 'South America', 'Peso', 'CLP', '', '56', '152', '^(d{7})$', 'yes', '.cl', 'CL.png', 1),
(46, 'China', 'People''s Republic of China', 'CN', 'CHN', 'Asia', 'Yuan Renminbi', 'CNY', '¥', '86', '156', '^(d{6})$', 'yes', '.cn', 'CN.png', 1),
(47, 'Christmas Island', 'Christmas Island', 'CX', 'CXR', 'Asia', 'Dollar', 'AUD', '$', '61', '162', '^(d{4})$', 'no', '.cx', 'CX.png', 1),
(48, 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'CC', 'CCK', NULL, 'Dollar', 'AUD', '$', '61', '166', NULL, 'no', '.cc', 'CC.png', 1),
(49, 'Colombia', 'Republic of Colombia', 'CO', 'COL', 'South America', 'Peso', 'COP', '$', '57', '170', '', 'yes', '.co', 'CO.png', 1),
(50, 'Comoros', 'Union of the Comoros', 'KM', 'COM', NULL, 'Franc', 'KMF', '', '269', '174', '', 'yes', '.km', 'KM.png', 1),
(51, 'Congo', 'Republic of the Congo', 'CG', 'COG', NULL, 'Franc', 'XAF', 'FCF', '242', '178', '', 'yes', '.cg', 'CG.png', 1),
(52, 'Cook Islands', 'Cook Islands', 'CK', 'COK', 'Australia/Oceania', 'Dollar', 'NZD', '$', '682', '184', '', 'some', '.ck', 'CK.png', 1),
(53, 'Costa Rica', 'Republic of Costa Rica', 'CR', 'CRI', 'North America', 'Colon', 'CRC', '₡', '506', '188', '^(d{4})$', 'yes', '.cr', 'CR.png', 1),
(54, 'Cote d''ivoire (Ivory Coast)', 'Republic of C&ocirc;te D''Ivoire (Ivory Coast)', 'CI', 'CIV', NULL, 'Franc', 'XOF', '', '225', '384', NULL, 'yes', '.ci', 'CI.png', 1),
(55, 'Croatia', 'Republic of Croatia', 'HR', 'HRV', 'Europe', 'Kuna', 'HRK', 'kn', '385', '191', '^(?:HR)*(d{5})$', 'yes', '.hr', 'HR.png', 1),
(56, 'Cuba', 'Republic of Cuba', 'CU', 'CUB', 'North America', 'Peso', 'CUP', '₱', '53', '192', '^(?:CP)*(d{5})$', 'yes', '.cu', 'CU.png', 1),
(57, 'Curacao', 'Cura&ccedil;ao', 'CW', 'CUW', NULL, NULL, NULL, NULL, '599', '531', NULL, 'no', '.cw', 'CW.png', 1),
(58, 'Cyprus', 'Republic of Cyprus', 'CY', 'CYP', 'Europe', 'Pound', 'CYP', '', '357', '196', '^(d{4})$', 'yes', '.cy', 'CY.png', 1),
(59, 'Czech Republic', 'Czech Republic', 'CZ', 'CZE', 'Europe', 'Koruna', 'CZK', 'Kč', '420', '203', '^(d{5})$', 'yes', '.cz', 'CZ.png', 1),
(60, 'Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'CD', 'COD', NULL, 'Franc', 'CDF', '', '243', '180', '', 'yes', '.cd', 'CD.png', 1),
(61, 'Denmark', 'Kingdom of Denmark', 'DK', 'DNK', 'Europe', 'Krone', 'DKK', 'kr', '45', '208', '^(d{4})$', 'yes', '.dk', 'DK.png', 1),
(62, 'Djibouti', 'Republic of Djibouti', 'DJ', 'DJI', NULL, 'Franc', 'DJF', '', '253', '262', '', 'yes', '.dj', 'DJ.png', 1),
(63, 'Dominica', 'Commonwealth of Dominica', 'DM', 'DMA', 'North America', 'Dollar', 'XCD', '$', '1+767', '212', '', 'yes', '.dm', 'DM.png', 1),
(64, 'Dominican Republic', 'Dominican Republic', 'DO', 'DOM', 'North America', 'Peso', 'DOP', 'RD$', '1+809, 8', '214', '^(d{5})$', 'yes', '.do', 'DO.png', 1),
(65, 'Ecuador', 'Republic of Ecuador', 'EC', 'ECU', 'South America', 'Dollar', 'USD', '$', '593', '218', '^([a-zA-Z]d{4}[a-zA-Z])$', 'yes', '.ec', 'EC.png', 1),
(66, 'Egypt', 'Arab Republic of Egypt', 'EG', 'EGY', NULL, 'Pound', 'EGP', '£', '20', '818', '^(d{5})$', 'yes', '.eg', 'EG.png', 1),
(67, 'El Salvador', 'Republic of El Salvador', 'SV', 'SLV', 'North America', 'Colone', 'SVC', '$', '503', '222', '^(?:CP)*(d{4})$', 'yes', '.sv', 'SV.png', 1),
(68, 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'GQ', 'GNQ', NULL, 'Franc', 'XAF', 'FCF', '240', '226', '', 'yes', '.gq', 'GQ.png', 1),
(69, 'Eritrea', 'State of Eritrea', 'ER', 'ERI', 'Africa', 'Nakfa', 'ERN', 'Nfk', '291', '232', '', 'yes', '.er', 'ER.png', 1),
(70, 'Estonia', 'Republic of Estonia', 'EE', 'EST', 'Europe', 'Kroon', 'EEK', 'kr', '372', '233', '^(d{5})$', 'yes', '.ee', 'EE.png', 1),
(71, 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ET', 'ETH', 'Africa', 'Birr', 'ETB', '', '251', '231', '^(d{4})$', 'yes', '.et', 'ET.png', 1),
(72, 'Falkland Islands (Malvinas)', 'The Falkland Islands (Malvinas)', 'FK', 'FLK', NULL, 'Pound', 'FKP', '£', '500', '238', NULL, 'no', '.fk', 'FK.png', 1),
(73, 'Faroe Islands', 'The Faroe Islands', 'FO', 'FRO', 'Europe', 'Krone', 'DKK', 'kr', '298', '234', '^(?:FO)*(d{3})$', 'no', '.fo', 'FO.png', 1),
(74, 'Fiji', 'Republic of Fiji', 'FJ', 'FJI', 'Australia/Oceania', 'Dollar', 'FJD', '$', '679', '242', '', 'yes', '.fj', 'FJ.png', 1),
(75, 'Finland', 'Republic of Finland', 'FI', 'FIN', 'Europe', 'Euro', 'EUR', '€', '358', '246', '^(?:FI)*(d{5})$', 'yes', '.fi', 'FI.png', 1),
(76, 'France', 'French Republic', 'FR', 'FRA', 'Europe', 'Euro', 'EUR', '€', '33', '250', '^(d{5})$', 'yes', '.fr', 'FR.png', 1),
(77, 'French Guiana', 'French Guiana', 'GF', 'GUF', 'South America', 'Euro', 'EUR', '€', '594', '254', '^((97)|(98)3d{2})$', 'no', '.gf', 'GF.png', 1),
(78, 'French Polynesia', 'French Polynesia', 'PF', 'PYF', 'Australia/Oceania', 'Franc', 'XPF', '', '689', '258', '^((97)|(98)7d{2})$', 'no', '.pf', 'PF.png', 1),
(79, 'French Southern Territories', 'French Southern Territories', 'TF', 'ATF', 'Antarctica', 'Euro  ', 'EUR', '€', NULL, '260', '', 'no', '.tf', 'TF.png', 1),
(80, 'Gabon', 'Gabonese Republic', 'GA', 'GAB', 'Africa', 'Franc', 'XAF', 'FCF', '241', '266', '', 'yes', '.ga', 'GA.png', 1),
(81, 'Gambia', 'Republic of The Gambia', 'GM', 'GMB', 'Africa', 'Dalasi', 'GMD', 'D', '220', '270', '', 'yes', '.gm', 'GM.png', 1),
(82, 'Georgia', 'Georgia', 'GE', 'GEO', 'Asia', 'Lari', 'GEL', '', '995', '268', '^(d{4})$', 'yes', '.ge', 'GE.png', 1),
(83, 'Germany', 'Federal Republic of Germany', 'DE', 'DEU', 'Europe', 'Euro', 'EUR', '€', '49', '276', '^(d{5})$', 'yes', '.de', 'DE.png', 1),
(84, 'Ghana', 'Republic of Ghana', 'GH', 'GHA', 'Africa', 'Cedi', 'GHC', '¢', '233', '288', '', 'yes', '.gh', 'GH.png', 1),
(85, 'Gibraltar', 'Gibraltar', 'GI', 'GIB', 'Europe', 'Pound', 'GIP', '£', '350', '292', '', 'no', '.gi', 'GI.png', 1),
(86, 'Greece', 'Hellenic Republic', 'GR', 'GRC', 'Europe', 'Euro', 'EUR', '€', '30', '300', '^(d{5})$', 'yes', '.gr', 'GR.png', 1),
(87, 'Greenland', 'Greenland', 'GL', 'GRL', 'North America', 'Krone', 'DKK', 'kr', '299', '304', '^(d{4})$', 'no', '.gl', 'GL.png', 1),
(88, 'Grenada', 'Grenada', 'GD', 'GRD', 'North America', 'Dollar', 'XCD', '$', '1+473', '308', '', 'yes', '.gd', 'GD.png', 1),
(89, 'Guadaloupe', 'Guadeloupe', 'GP', 'GLP', 'North America', 'Euro', 'EUR', '€', '590', '312', '^((97)|(98)d{3})$', 'no', '.gp', 'GP.png', 1),
(90, 'Guam', 'Guam', 'GU', 'GUM', 'Australia/Oceania', 'Dollar', 'USD', '$', '1+671', '316', '^(969d{2})$', 'no', '.gu', 'GU.png', 1),
(91, 'Guatemala', 'Republic of Guatemala', 'GT', 'GTM', 'North America', 'Quetzal', 'GTQ', 'Q', '502', '320', '^(d{5})$', 'yes', '.gt', 'GT.png', 1),
(92, 'Guernsey', 'Guernsey', 'GG', 'GGY', 'Europe', NULL, NULL, NULL, '44', '831', '^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A', 'no', '.gg', 'GG.png', 1),
(93, 'Guinea', 'Republic of Guinea', 'GN', 'GIN', 'Africa', 'Franc', 'GNF', '', '224', '324', '', 'yes', '.gn', 'GN.png', 1),
(94, 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'GW', 'GNB', 'Africa', 'Franc', 'XOF', '', '245', '624', '^(d{4})$', 'yes', '.gw', 'GW.png', 1),
(95, 'Guyana', 'Co-operative Republic of Guyana', 'GY', 'GUY', 'South America', 'Dollar', 'GYD', '$', '592', '328', '', 'yes', '.gy', 'GY.png', 1),
(96, 'Haiti', 'Republic of Haiti', 'HT', 'HTI', 'North America', 'Gourde', 'HTG', 'G', '509', '332', '^(?:HT)*(d{4})$', 'yes', '.ht', 'HT.png', 1),
(97, 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HM', 'HMD', 'Antarctica', 'Dollar', 'AUD', '$', 'NONE', '334', '', 'no', '.hm', 'HM.png', 1),
(98, 'Honduras', 'Republic of Honduras', 'HN', 'HND', 'North America', 'Lempira', 'HNL', 'L', '504', '340', '^([A-Z]{2}d{4})$', 'yes', '.hn', 'HN.png', 1),
(99, 'Hong Kong', 'Hong Kong', 'HK', 'HKG', 'Asia', 'Dollar', 'HKD', '$', '852', '344', '', 'no', '.hk', 'HK.png', 1),
(100, 'Hungary', 'Hungary', 'HU', 'HUN', 'Europe', 'Forint', 'HUF', 'Ft', '36', '348', '^(d{4})$', 'yes', '.hu', 'HU.png', 1),
(101, 'Iceland', 'Republic of Iceland', 'IS', 'ISL', 'Europe', 'Krona', 'ISK', 'kr', '354', '352', '^(d{3})$', 'yes', '.is', 'IS.png', 1),
(102, 'India', 'Republic of India', 'IN', 'IND', 'Asia', 'Rupee', 'INR', '₹', '91', '356', '^(d{6})$', 'yes', '.in', 'IN.png', 1),
(103, 'Indonesia', 'Republic of Indonesia', 'ID', 'IDN', 'Asia', 'Rupiah', 'IDR', 'Rp', '62', '360', '^(d{5})$', 'yes', '.id', 'ID.png', 1),
(104, 'Iran', 'Islamic Republic of Iran', 'IR', 'IRN', 'Asia', 'Rial', 'IRR', '﷼', '98', '364', '^(d{10})$', 'yes', '.ir', 'IR.png', 1),
(105, 'Iraq', 'Republic of Iraq', 'IQ', 'IRQ', 'Asia', 'Dinar', 'IQD', '', '964', '368', '^(d{5})$', 'yes', '.iq', 'IQ.png', 1),
(106, 'Ireland', 'Ireland', 'IE', 'IRL', 'Europe', 'Euro', 'EUR', '€', '353', '372', '', 'yes', '.ie', 'IE.png', 1),
(107, 'Isle of Man', 'Isle of Man', 'IM', 'IMN', 'Europe', NULL, NULL, NULL, '44', '833', '^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A', 'no', '.im', 'IM.png', 1),
(108, 'Israel', 'State of Israel', 'IL', 'ISR', 'Asia', 'Shekel', 'ILS', '₪', '972', '376', '^(d{5})$', 'yes', '.il', 'IL.png', 1),
(109, 'Italy', 'Italian Republic', 'IT', 'ITA', 'Europe', 'Euro', 'EUR', '€', '39', '380', '^(d{5})$', 'yes', '.jm', 'IT.png', 1),
(110, 'Jamaica', 'Jamaica', 'JM', 'JAM', 'North America', 'Dollar', 'JMD', '$', '1+876', '388', '', 'yes', '.jm', 'JM.png', 1),
(111, 'Japan', 'Japan', 'JP', 'JPN', 'Asia', 'Yen', 'JPY', '¥', '81', '392', '^(d{7})$', 'yes', '.jp', 'JP.png', 1),
(112, 'Jersey', 'The Bailiwick of Jersey', 'JE', 'JEY', 'Europe', NULL, NULL, NULL, '44', '832', '^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A', 'no', '.je', 'JE.png', 1),
(113, 'Jordan', 'Hashemite Kingdom of Jordan', 'JO', 'JOR', 'Asia', 'Dinar', 'JOD', '', '962', '400', '^(d{5})$', 'yes', '.jo', 'JO.png', 1),
(114, 'Kazakhstan', 'Republic of Kazakhstan', 'KZ', 'KAZ', 'Asia', 'Tenge', 'KZT', 'лв', '7', '398', '^(d{6})$', 'yes', '.kz', 'KZ.png', 1),
(115, 'Kenya', 'Republic of Kenya', 'KE', 'KEN', 'Africa', 'Shilling', 'KES', '', '254', '404', '^(d{5})$', 'yes', '.ke', 'KE.png', 1),
(116, 'Kiribati', 'Republic of Kiribati', 'KI', 'KIR', 'Australia/Oceania', 'Dollar', 'AUD', '$', '686', '296', '', 'yes', '.ki', 'KI.png', 1),
(117, 'Kosovo', 'Republic of Kosovo', 'XK', '---', 'Europe', NULL, NULL, NULL, '381', '---', '', 'some', '', 'XK.png', 1),
(118, 'Kuwait', 'State of Kuwait', 'KW', 'KWT', 'Asia', 'Dinar', 'KWD', '', '965', '414', '^(d{5})$', 'yes', '.kw', 'KW.png', 1),
(119, 'Kyrgyzstan', 'Kyrgyz Republic', 'KG', 'KGZ', 'Asia', 'Som', 'KGS', 'лв', '996', '417', '^(d{6})$', 'yes', '.kg', 'KG.png', 1),
(120, 'Laos', 'Lao People''s Democratic Republic', 'LA', 'LAO', 'Asia', 'Kip', 'LAK', '₭', '856', '418', '^(d{5})$', 'yes', '.la', 'LA.png', 1),
(121, 'Latvia', 'Republic of Latvia', 'LV', 'LVA', 'Europe', 'Lat', 'LVL', 'Ls', '371', '428', '^(?:LV)*(d{4})$', 'yes', '.lv', 'LV.png', 1),
(122, 'Lebanon', 'Republic of Lebanon', 'LB', 'LBN', 'Asia', 'Pound', 'LBP', '£', '961', '422', '^(d{4}(d{4})?)$', 'yes', '.lb', 'LB.png', 1),
(123, 'Lesotho', 'Kingdom of Lesotho', 'LS', 'LSO', 'Africa', 'Loti', 'LSL', 'L', '266', '426', '^(d{3})$', 'yes', '.ls', 'LS.png', 1),
(124, 'Liberia', 'Republic of Liberia', 'LR', 'LBR', 'Africa', 'Dollar', 'LRD', '$', '231', '430', '^(d{4})$', 'yes', '.lr', 'LR.png', 1),
(125, 'Libya', 'Libya', 'LY', 'LBY', 'Africa', 'Dinar', 'LYD', '', '218', '434', '', 'yes', '.ly', 'LY.png', 1),
(126, 'Liechtenstein', 'Principality of Liechtenstein', 'LI', 'LIE', 'Europe', 'Franc', 'CHF', 'CHF', '423', '438', '^(d{4})$', 'yes', '.li', 'LI.png', 1),
(127, 'Lithuania', 'Republic of Lithuania', 'LT', 'LTU', 'Europe', 'Litas', 'LTL', 'Lt', '370', '440', '^(?:LT)*(d{5})$', 'yes', '.lt', 'LT.png', 1),
(128, 'Luxembourg', 'Grand Duchy of Luxembourg', 'LU', 'LUX', 'Europe', 'Euro', 'EUR', '€', '352', '442', '^(d{4})$', 'yes', '.lu', 'LU.png', 1),
(129, 'Macao', 'The Macao Special Administrative Region', 'MO', 'MAC', 'Asia', 'Pataca', 'MOP', 'MOP', '853', '446', '', 'no', '.mo', 'MO.png', 1),
(130, 'Macedonia', 'The Former Yugoslav Republic of Macedonia', 'MK', 'MKD', 'Europe', 'Denar', 'MKD', 'ден', '389', '807', '^(d{4})$', 'yes', '.mk', 'MK.png', 1),
(131, 'Madagascar', 'Republic of Madagascar', 'MG', 'MDG', 'Africa', 'Ariary', 'MGA', '', '261', '450', '^(d{3})$', 'yes', '.mg', 'MG.png', 1),
(132, 'Malawi', 'Republic of Malawi', 'MW', 'MWI', 'Africa', 'Kwacha', 'MWK', 'MK', '265', '454', '', 'yes', '.mw', 'MW.png', 1),
(133, 'Malaysia', 'Malaysia', 'MY', 'MYS', 'Asia', 'Ringgit', 'MYR', 'RM', '60', '458', '^(d{5})$', 'yes', '.my', 'MY.png', 1),
(134, 'Maldives', 'Republic of Maldives', 'MV', 'MDV', 'Asia', 'Rufiyaa', 'MVR', 'Rf', '960', '462', '^(d{5})$', 'yes', '.mv', 'MV.png', 1),
(135, 'Mali', 'Republic of Mali', 'ML', 'MLI', 'Africa', 'Franc', 'XOF', '', '223', '466', '', 'yes', '.ml', 'ML.png', 1),
(136, 'Malta', 'Republic of Malta', 'MT', 'MLT', 'Europe', 'Lira', 'MTL', '', '356', '470', '^([A-Z]{3}d{2}d?)$', 'yes', '.mt', 'MT.png', 1),
(137, 'Marshall Islands', 'Republic of the Marshall Islands', 'MH', 'MHL', 'Australia/Oceania', 'Dollar', 'USD', '$', '692', '584', '', 'yes', '.mh', 'MH.png', 1),
(138, 'Martinique', 'Martinique', 'MQ', 'MTQ', 'North America', 'Euro', 'EUR', '€', '596', '474', '^(d{5})$', 'no', '.mq', 'MQ.png', 1),
(139, 'Mauritania', 'Islamic Republic of Mauritania', 'MR', 'MRT', 'Africa', 'Ouguiya', 'MRO', 'UM', '222', '478', '', 'yes', '.mr', 'MR.png', 1),
(140, 'Mauritius', 'Republic of Mauritius', 'MU', 'MUS', 'Africa', 'Rupee', 'MUR', '₨', '230', '480', '', 'yes', '.mu', 'MU.png', 1),
(141, 'Mayotte', 'Mayotte', 'YT', 'MYT', 'Africa', 'Euro', 'EUR', '€', '262', '175', '^(d{5})$', 'no', '.yt', 'YT.png', 1),
(142, 'Mexico', 'United Mexican States', 'MX', 'MEX', 'North America', 'Peso', 'MXN', '$', '52', '484', '^(d{5})$', 'yes', '.mx', 'MX.png', 1),
(143, 'Micronesia', 'Federated States of Micronesia', 'FM', 'FSM', 'Australia/Oceania', 'Dollar', 'USD', '$', '691', '583', '^(d{5})$', 'yes', '.fm', 'FM.png', 1),
(144, 'Moldava', 'Republic of Moldova', 'MD', 'MDA', NULL, 'Leu', 'MDL', '', '373', '498', NULL, 'yes', '.md', 'MD.png', 1),
(145, 'Monaco', 'Principality of Monaco', 'MC', 'MCO', 'Europe', 'Euro', 'EUR', '€', '377', '492', '^(d{5})$', 'yes', '.mc', 'MC.png', 1),
(146, 'Mongolia', 'Mongolia', 'MN', 'MNG', 'Asia', 'Tugrik', 'MNT', '₮', '976', '496', '^(d{6})$', 'yes', '.mn', 'MN.png', 1),
(147, 'Montenegro', 'Montenegro', 'ME', 'MNE', 'Europe', NULL, NULL, NULL, '382', '499', '^(d{5})$', 'yes', '.me', 'ME.png', 1),
(148, 'Montserrat', 'Montserrat', 'MS', 'MSR', 'North America', 'Dollar', 'XCD', '$', '1+664', '500', '', 'no', '.ms', 'MS.png', 1),
(149, 'Morocco', 'Kingdom of Morocco', 'MA', 'MAR', 'Africa', 'Dirham', 'MAD', '', '212', '504', '^(d{5})$', 'yes', '.ma', 'MA.png', 1),
(150, 'Mozambique', 'Republic of Mozambique', 'MZ', 'MOZ', 'Africa', 'Meticail', 'MZN', 'MT', '258', '508', '^(d{4})$', 'yes', '.mz', 'MZ.png', 1),
(151, 'Myanmar (Burma)', 'Republic of the Union of Myanmar', 'MM', 'MMR', NULL, 'Kyat', 'MMK', 'K', '95', '104', NULL, 'yes', '.mm', 'MM.png', 1),
(152, 'Namibia', 'Republic of Namibia', 'NA', 'NAM', 'Africa', 'Dollar', 'NAD', '$', '264', '516', '', 'yes', '.na', 'NA.png', 1),
(153, 'Nauru', 'Republic of Nauru', 'NR', 'NRU', 'Australia/Oceania', 'Dollar', 'AUD', '$', '674', '520', '', 'yes', '.nr', 'NR.png', 1),
(154, 'Nepal', 'Federal Democratic Republic of Nepal', 'NP', 'NPL', 'Asia', 'Rupee', 'NPR', '₨', '977', '524', '^(d{5})$', 'yes', '.np', 'NP.png', 1),
(155, 'Netherlands', 'Kingdom of the Netherlands', 'NL', 'NLD', 'Europe', 'Euro', 'EUR', '€', '31', '528', '^(d{4}[A-Z]{2})$', 'yes', '.nl', 'NL.png', 1),
(156, 'New Caledonia', 'New Caledonia', 'NC', 'NCL', 'Australia/Oceania', 'Franc', 'XPF', '', '687', '540', '^(d{5})$', 'no', '.nc', 'NC.png', 1),
(157, 'New Zealand', 'New Zealand', 'NZ', 'NZL', 'Australia/Oceania', 'Dollar', 'NZD', '$', '64', '554', '^(d{4})$', 'yes', '.nz', 'NZ.png', 1),
(158, 'Nicaragua', 'Republic of Nicaragua', 'NI', 'NIC', 'North America', 'Cordoba', 'NIO', 'C$', '505', '558', '^(d{7})$', 'yes', '.ni', 'NI.png', 1),
(159, 'Niger', 'Republic of Niger', 'NE', 'NER', 'Africa', 'Franc', 'XOF', '', '227', '562', '^(d{4})$', 'yes', '.ne', 'NE.png', 1),
(160, 'Nigeria', 'Federal Republic of Nigeria', 'NG', 'NGA', 'Africa', 'Naira', 'NGN', '₦', '234', '566', '^(d{6})$', 'yes', '.ng', 'NG.png', 1),
(161, 'Niue', 'Niue', 'NU', 'NIU', 'Australia/Oceania', 'Dollar', 'NZD', '$', '683', '570', '', 'some', '.nu', 'NU.png', 1),
(162, 'Norfolk Island', 'Norfolk Island', 'NF', 'NFK', 'Australia/Oceania', 'Dollar', 'AUD', '$', '672', '574', '', 'no', '.nf', 'NF.png', 1),
(163, 'North Korea', 'Democratic People''s Republic of Korea', 'KP', 'PRK', 'Asia', 'Won', 'KPW', '₩', '850', '408', '^(d{6})$', 'yes', '.kp', 'KP.png', 1),
(164, 'Northern Mariana Islands', 'Northern Mariana Islands', 'MP', 'MNP', 'Australia/Oceania', 'Dollar', 'USD', '$', '1+670', '580', '', 'no', '.mp', 'MP.png', 1),
(165, 'Norway', 'Kingdom of Norway', 'NO', 'NOR', 'Europe', 'Krone', 'NOK', 'kr', '47', '578', '^(d{4})$', 'yes', '.no', 'NO.png', 1),
(166, 'Oman', 'Sultanate of Oman', 'OM', 'OMN', 'Asia', 'Rial', 'OMR', '﷼', '968', '512', '^(d{3})$', 'yes', '.om', 'OM.png', 1),
(167, 'Pakistan', 'Islamic Republic of Pakistan', 'PK', 'PAK', 'Asia', 'Rupee', 'PKR', '₨', '92', '586', '^(d{5})$', 'yes', '.pk', 'PK.png', 1),
(168, 'Palau', 'Republic of Palau', 'PW', 'PLW', 'Australia/Oceania', 'Dollar', 'USD', '$', '680', '585', '^(96940)$', 'yes', '.pw', 'PW.png', 1),
(169, 'Palestine', 'State of Palestine (or Occupied Palestinian Territory)', 'PS', 'PSE', NULL, 'Shekel', 'ILS', '₪', '970', '275', NULL, 'some', '.ps', 'PS.png', 1),
(170, 'Panama', 'Republic of Panama', 'PA', 'PAN', 'North America', 'Balboa', 'PAB', 'B/.', '507', '591', '', 'yes', '.pa', 'PA.png', 1),
(171, 'Papua New Guinea', 'Independent State of Papua New Guinea', 'PG', 'PNG', 'Australia/Oceania', 'Kina', 'PGK', '', '675', '598', '^(d{3})$', 'yes', '.pg', 'PG.png', 1),
(172, 'Paraguay', 'Republic of Paraguay', 'PY', 'PRY', 'South America', 'Guarani', 'PYG', 'Gs', '595', '600', '^(d{4})$', 'yes', '.py', 'PY.png', 1),
(173, 'Peru', 'Republic of Peru', 'PE', 'PER', 'South America', 'Sol', 'PEN', 'S/.', '51', '604', '', 'yes', '.pe', 'PE.png', 1),
(174, 'Phillipines', 'Republic of the Philippines', 'PH', 'PHL', NULL, 'Peso', 'PHP', 'Php', '63', '608', NULL, 'yes', '.ph', 'PH.png', 1),
(175, 'Pitcairn', 'Pitcairn', 'PN', 'PCN', 'Australia/Oceania', 'Dollar', 'NZD', '$', 'NONE', '612', '', 'no', '.pn', 'PN.png', 1),
(176, 'Poland', 'Republic of Poland', 'PL', 'POL', 'Europe', 'Zloty', 'PLN', 'zł', '48', '616', '^(d{5})$', 'yes', '.pl', 'PL.png', 1),
(177, 'Portugal', 'Portuguese Republic', 'PT', 'PRT', 'Europe', 'Euro', 'EUR', '€', '351', '620', '^(d{7})$', 'yes', '.pt', 'PT.png', 1),
(178, 'Puerto Rico', 'Commonwealth of Puerto Rico', 'PR', 'PRI', 'North America', 'Dollar', 'USD', '$', '1+939', '630', '^(d{9})$', 'no', '.pr', 'PR.png', 1),
(179, 'Qatar', 'State of Qatar', 'QA', 'QAT', 'Asia', 'Rial', 'QAR', '﷼', '974', '634', '', 'yes', '.qa', 'QA.png', 1),
(180, 'Reunion', 'R&eacute;union', 'RE', 'REU', 'Africa', 'Euro', 'EUR', '€', '262', '638', '^((97)|(98)(4|7|8)d{2})$', 'no', '.re', 'RE.png', 1),
(181, 'Romania', 'Romania', 'RO', 'ROU', 'Europe', 'Leu', 'RON', 'lei', '40', '642', '^(d{6})$', 'yes', '.ro', 'RO.png', 1),
(182, 'Russia', 'Russian Federation', 'RU', 'RUS', 'Europe', 'Ruble', 'RUB', 'руб', '7', '643', '^(d{6})$', 'yes', '.ru', 'RU.png', 1),
(183, 'Rwanda', 'Republic of Rwanda', 'RW', 'RWA', 'Africa', 'Franc', 'RWF', '', '250', '646', '', 'yes', '.rw', 'RW.png', 1),
(184, 'Saint Barthelemy', 'Saint Barth&eacute;lemy', 'BL', 'BLM', 'North America', NULL, NULL, NULL, '590', '652', '', 'no', '.bl', 'BL.png', 1),
(185, 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 'Africa', 'Pound', 'SHP', '£', '290', '654', '^(STHL1ZZ)$', 'no', '.sh', 'SH.png', 1),
(186, 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'KN', 'KNA', 'North America', 'Dollar', 'XCD', '$', '1+869', '659', '', 'yes', '.kn', 'KN.png', 1),
(187, 'Saint Lucia', 'Saint Lucia', 'LC', 'LCA', 'North America', 'Dollar', 'XCD', '$', '1+758', '662', '', 'yes', '.lc', 'LC.png', 1),
(188, 'Saint Martin', 'Saint Martin', 'MF', 'MAF', 'North America', NULL, NULL, NULL, '590', '663', '', 'no', '.mf', 'MF.png', 1),
(189, 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'PM', 'SPM', 'North America', 'Euro', 'EUR', '€', '508', '666', '^(97500)$', 'no', '.pm', 'PM.png', 1),
(190, 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'North America', 'Dollar', 'XCD', '$', '1+784', '670', '', 'yes', '.vc', 'VC.png', 1),
(191, 'Samoa', 'Independent State of Samoa', 'WS', 'WSM', 'Australia/Oceania', 'Tala', 'WST', 'WS$', '685', '882', '', 'yes', '.ws', 'WS.png', 1),
(192, 'San Marino', 'Republic of San Marino', 'SM', 'SMR', 'Europe', 'Euro', 'EUR', '€', '378', '674', '^(4789d)$', 'yes', '.sm', 'SM.png', 1),
(193, 'Sao Tome and Principe', 'Democratic Republic of S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'ST', 'STP', 'Africa', 'Dobra', 'STD', 'Db', '239', '678', '', 'yes', '.st', 'ST.png', 1),
(194, 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'SA', 'SAU', 'Asia', 'Rial', 'SAR', '﷼', '966', '682', '^(d{5})$', 'yes', '.sa', 'SA.png', 1),
(195, 'Senegal', 'Republic of Senegal', 'SN', 'SEN', 'Africa', 'Franc', 'XOF', '', '221', '686', '^(d{5})$', 'yes', '.sn', 'SN.png', 1),
(196, 'Serbia', 'Republic of Serbia', 'RS', 'SRB', 'Europe', NULL, NULL, NULL, '381', '688', '^(d{6})$', 'yes', '.rs', 'RS.png', 1),
(197, 'Seychelles', 'Republic of Seychelles', 'SC', 'SYC', 'Africa', 'Rupee', 'SCR', '₨', '248', '690', '', 'yes', '.sc', 'SC.png', 1),
(198, 'Sierra Leone', 'Republic of Sierra Leone', 'SL', 'SLE', 'Africa', 'Leone', 'SLL', 'Le', '232', '694', '', 'yes', '.sl', 'SL.png', 1),
(199, 'Singapore', 'Republic of Singapore', 'SG', 'SGP', 'Asia', 'Dollar', 'SGD', '$', '65', '702', '^(d{6})$', 'yes', '.sg', 'SG.png', 1),
(200, 'Sint Maarten', 'Sint Maarten', 'SX', 'SXM', NULL, NULL, NULL, NULL, '1+721', '534', NULL, 'no', '.sx', 'SX.png', 1),
(201, 'Slovakia', 'Slovak Republic', 'SK', 'SVK', 'Europe', 'Koruna', 'SKK', 'Sk', '421', '703', '^(d{5})$', 'yes', '.sk', 'SK.png', 1),
(202, 'Slovenia', 'Republic of Slovenia', 'SI', 'SVN', 'Europe', 'Euro', 'EUR', '€', '386', '705', '^(?:SI)*(d{4})$', 'yes', '.si', 'SI.png', 1),
(203, 'Solomon Islands', 'Solomon Islands', 'SB', 'SLB', 'Australia/Oceania', 'Dollar', 'SBD', '$', '677', '090', '', 'yes', '.sb', 'SB.png', 1),
(204, 'Somalia', 'Somali Republic', 'SO', 'SOM', 'Africa', 'Shilling', 'SOS', 'S', '252', '706', '^([A-Z]{2}d{5})$', 'yes', '.so', 'SO.png', 1),
(205, 'South Africa', 'Republic of South Africa', 'ZA', 'ZAF', 'Africa', 'Rand', 'ZAR', 'R', '27', '710', '^(d{4})$', 'yes', '.za', 'ZA.png', 1),
(206, 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 'Antarctica', 'Pound', 'GBP', '£', '500', '239', '', 'no', '.gs', 'GS.png', 1),
(207, 'South Korea', 'Republic of Korea', 'KR', 'KOR', 'Asia', 'Won', 'KRW', '₩', '82', '410', '^(?:SEOUL)*(d{6})$', 'yes', '.kr', 'KR.png', 1),
(208, 'South Sudan', 'Republic of South Sudan', 'SS', 'SSD', NULL, NULL, NULL, NULL, '211', '728', NULL, 'yes', '.ss', 'SS.png', 1),
(209, 'Spain', 'Kingdom of Spain', 'ES', 'ESP', 'Europe', 'Euro', 'EUR', '€', '34', '724', '^(d{5})$', 'yes', '.es', 'ES.png', 1),
(210, 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LK', 'LKA', 'Asia', 'Rupee', 'LKR', '₨', '94', '144', '^(d{5})$', 'yes', '.lk', 'LK.png', 1),
(211, 'Sudan', 'Republic of the Sudan', 'SD', 'SDN', 'Africa', 'Dinar', 'SDD', '', '249', '729', '^(d{5})$', 'yes', '.sd', 'SD.png', 1),
(212, 'Suriname', 'Republic of Suriname', 'SR', 'SUR', 'South America', 'Dollar', 'SRD', '$', '597', '740', '', 'yes', '.sr', 'SR.png', 1),
(213, 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'SJ', 'SJM', 'Europe', 'Krone', 'NOK', 'kr', '47', '744', '', 'no', '.sj', 'SJ.png', 1),
(214, 'Swaziland', 'Kingdom of Swaziland', 'SZ', 'SWZ', 'Africa', 'Lilangeni', 'SZL', '', '268', '748', '^([A-Z]d{3})$', 'yes', '.sz', 'SZ.png', 1),
(215, 'Sweden', 'Kingdom of Sweden', 'SE', 'SWE', 'Europe', 'Krona', 'SEK', 'kr', '46', '752', '^(?:SE)*(d{5})$', 'yes', '.se', 'SE.png', 1),
(216, 'Switzerland', 'Swiss Confederation', 'CH', 'CHE', 'Europe', 'Franc', 'CHF', 'CHF', '41', '756', '^(d{4})$', 'yes', '.ch', 'CH.png', 1),
(217, 'Syria', 'Syrian Arab Republic', 'SY', 'SYR', 'Asia', 'Pound', 'SYP', '£', '963', '760', '', 'yes', '.sy', 'SY.png', 1),
(218, 'Taiwan', 'Republic of China (Taiwan)', 'TW', 'TWN', 'Asia', 'Dollar', 'TWD', 'NT$', '886', '158', '^(d{5})$', 'former', '.tw', 'TW.png', 1),
(219, 'Tajikistan', 'Republic of Tajikistan', 'TJ', 'TJK', 'Asia', 'Somoni', 'TJS', '', '992', '762', '^(d{6})$', 'yes', '.tj', 'TJ.png', 1),
(220, 'Tanzania', 'United Republic of Tanzania', 'TZ', 'TZA', 'Africa', 'Shilling', 'TZS', '', '255', '834', '', 'yes', '.tz', 'TZ.png', 1),
(221, 'Thailand', 'Kingdom of Thailand', 'TH', 'THA', 'Asia', 'Baht', 'THB', '฿', '66', '764', '^(d{5})$', 'yes', '.th', 'TH.png', 1),
(222, 'Timor-Leste (East Timor)', 'Democratic Republic of Timor-Leste', 'TL', 'TLS', NULL, 'Dollar', 'USD', '$', '670', '626', NULL, 'yes', '.tl', 'TL.png', 1),
(223, 'Togo', 'Togolese Republic', 'TG', 'TGO', 'Africa', 'Franc', 'XOF', '', '228', '768', '', 'yes', '.tg', 'TG.png', 1),
(224, 'Tokelau', 'Tokelau', 'TK', 'TKL', 'Australia/Oceania', 'Dollar', 'NZD', '$', '690', '772', '', 'no', '.tk', 'TK.png', 1),
(225, 'Tonga', 'Kingdom of Tonga', 'TO', 'TON', 'Australia/Oceania', 'Pa''anga', 'TOP', 'T$', '676', '776', '', 'yes', '.to', 'TO.png', 1),
(226, 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TT', 'TTO', 'North America', 'Dollar', 'TTD', 'TT$', '1+868', '780', '', 'yes', '.tt', 'TT.png', 1),
(227, 'Tunisia', 'Republic of Tunisia', 'TN', 'TUN', 'Africa', 'Dinar', 'TND', '', '216', '788', '^(d{4})$', 'yes', '.tn', 'TN.png', 1),
(228, 'Turkey', 'Republic of Turkey', 'TR', 'TUR', 'Asia', 'Lira', 'TRY', 'YTL', '90', '792', '^(d{5})$', 'yes', '.tr', 'TR.png', 1),
(229, 'Turkmenistan', 'Turkmenistan', 'TM', 'TKM', 'Asia', 'Manat', 'TMM', 'm', '993', '795', '^(d{6})$', 'yes', '.tm', 'TM.png', 1),
(230, 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'TC', 'TCA', 'North America', 'Dollar', 'USD', '$', '1+649', '796', '^(TKCA 1ZZ)$', 'no', '.tc', 'TC.png', 1),
(231, 'Tuvalu', 'Tuvalu', 'TV', 'TUV', 'Australia/Oceania', 'Dollar', 'AUD', '$', '688', '798', '', 'yes', '.tv', 'TV.png', 1),
(232, 'Uganda', 'Republic of Uganda', 'UG', 'UGA', 'Africa', 'Shilling', 'UGX', '', '256', '800', '', 'yes', '.ug', 'UG.png', 1),
(233, 'Ukraine', 'Ukraine', 'UA', 'UKR', 'Europe', 'Hryvnia', 'UAH', '₴', '380', '804', '^(d{5})$', 'yes', '.ua', 'UA.png', 1),
(234, 'United Arab Emirates', 'United Arab Emirates', 'AE', 'ARE', 'Asia', 'Dirham', 'AED', 'د.إ', '971', '784', '', 'yes', '.ae', 'AE.png', 1),
(235, 'United Kingdom', 'United Kingdom of Great Britain and Nothern Ireland', 'GB', 'GBR', 'Europe', 'Pound', 'GBP', '£', '44', '826', '^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A', 'yes', '.uk', 'GB.png', 1),
(236, 'United States', 'United States of America', 'US', 'USA', 'North America', 'Dollar', 'USD', '$', '1', '840', '^(d{9})$', 'yes', '.us', 'US.png', 1),
(237, 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UM', 'UMI', 'Australia/Oceania', 'Dollar ', 'USD', '$', 'NONE', '581', '', 'no', 'NONE', 'UM.png', 1),
(238, 'Uruguay', 'Eastern Republic of Uruguay', 'UY', 'URY', 'South America', 'Peso', 'UYU', '$U', '598', '858', '^(d{5})$', 'yes', '.uy', 'UY.png', 1),
(239, 'Uzbekistan', 'Republic of Uzbekistan', 'UZ', 'UZB', 'Asia', 'Som', 'UZS', 'лв', '998', '860', '^(d{6})$', 'yes', '.uz', 'UZ.png', 1),
(240, 'Vanuatu', 'Republic of Vanuatu', 'VU', 'VUT', 'Australia/Oceania', 'Vatu', 'VUV', 'Vt', '678', '548', '', 'yes', '.vu', 'VU.png', 1),
(241, 'Vatican City', 'State of the Vatican City', 'VA', 'VAT', NULL, 'Euro', 'EUR', '€', '39', '336', NULL, 'no', '.va', 'VA.png', 1),
(242, 'Venezuela', 'Bolivarian Republic of Venezuela', 'VE', 'VEN', 'South America', 'Bolivar', 'VEF', 'Bs', '58', '862', '^(d{4})$', 'yes', '.ve', 'VE.png', 1),
(243, 'Vietnam', 'Socialist Republic of Vietnam', 'VN', 'VNM', 'Asia', 'Dong', 'VND', '₫', '84', '704', '^(d{6})$', 'yes', '.vn', 'VN.png', 1),
(244, 'Virgin Islands, British', 'British Virgin Islands', 'VG', 'VGB', 'North America', 'Dollar', 'USD', '$', '1+284', '092', '', 'no', '.vg', 'VG.png', 1),
(245, 'Virgin Islands, US', 'Virgin Islands of the United States', 'VI', 'VIR', NULL, 'Dollar', 'USD', '$', '1+340', '850', NULL, 'no', '.vi', 'VI.png', 1),
(246, 'Wallis and Futuna', 'Wallis and Futuna', 'WF', 'WLF', 'Australia/Oceania', 'Franc', 'XPF', '', '681', '876', '^(986d{2})$', 'no', '.wf', 'WF.png', 1),
(247, 'Western Sahara', 'Western Sahara', 'EH', 'ESH', 'Africa', 'Dirham', 'MAD', '', '212', '732', '', 'no', '.eh', 'EH.png', 1),
(248, 'Yemen', 'Republic of Yemen', 'YE', 'YEM', 'Asia', 'Rial', 'YER', '﷼', '967', '887', '', 'yes', '.ye', 'YE.png', 1),
(249, 'Zambia', 'Republic of Zambia', 'ZM', 'ZMB', 'Africa', 'Kwacha', 'ZMK', 'ZK', '260', '894', '^(d{5})$', 'yes', '.zm', 'ZM.png', 1),
(250, 'Zimbabwe', 'Republic of Zimbabwe', 'ZW', 'ZWE', 'Africa', 'Dollar', 'ZWD', 'Z$', '263', '716', '', 'yes', '.zw', 'ZW.png', 1);
-- --------------------------------------------------------
